### ISSUE TITLE
Is a "ready" check necessary for inbound events?

### ISSUE THREAD

**Issue by hufftheweevil** [zwave-js/node-red-contrib-zwave-js#20]
I recently discovered that the reason I'm not getting most messages from _battery powered devices_ immediately after restarting the node (or Node-RED altogether) is because of the `if (NodesReady.indexOf(ND.id) > 1)` check that is done for all inbound events. Is this check necessary?

It seems that most _battery powered devices_ (that have previously been interviewed and data cached) will start with an InterviewStatus of `RestartFromCache`. And they won't emit the `ready` event until after they wake up, which could be minutes or hours later. I don't think we should ignore inbound messages for nodes that have not emitted `ready`.

Or maybe we should. But that would mean this is actually an issue with `zwave-js`. I'm trying to learn more about the whole interview process for _battery powered devices_ by reading through the code, but it's not light reading... Any insight into this would be appreciated.

**Comment by marcus-j-davies** [comment]
`RestartFromCache` is kind of a 'I know about it, but now I'm back, let's catch up' kind of thing.
it does this to update its cache after a restart.

`RestartFromCache` will occur for all nodes , but non-battery devices will quickly have been re-interviewed, so you don't see it

The reason I have opted to filter nodes that have not fired `ready` is during the interview, it fires all the value updates (interview process includes fetching all its values).

You do however raise an interesting point, we maybe could make `RestartFromCache` exempt from this filter, not sure how best to implement it though.

**Comment by marcus-j-davies** [comment]
`RestartFromCache` is kind of a 'I know about it, but now I'm back, let's catch up' kind of thing.
it does this to update its cache after a restart.

`RestartFromCache` will occur for all nodes, but powered devices will quickly have been re-interviewed, so you don't see it.

The reason I have opted to filter nodes that have not fired `ready`, is during the interview, it fires all the value updates 
(interview process includes fetching all its values) and I don't want users to try and interact with devices that really aren't ready, the nodes status changes to show what nodes can be interacted with.

You do however raise an interesting point, we could make `RestartFromCache` exempt from this filter.
generally speaking, devices under `RestartFromCache` are safe to interact with (as z-wave js, already knows its setup), Evan though they may not respond right away, due to their sleeping status (hence the message gets queued)

So, one way we can do this, is to read the cache our self, and check for iether `Complete` or `RestartFromCache` and for each node found with that status, add it to the `NodesReady` collection - we do all this at start up, before zwave-js kicks in.

I have set the cache location to `/%home%./node-red/zwave-js-cache`

**Comment by marcus-j-davies** [comment]
Ok,

I have pushed to dev some changes, that should significantly speed up comms with battery operated devices.
Though we may get a lot of value updates - when these devices wake up (which I suppose isn't really a bad thing).

These pushes also expose some more CC's using managed mode.

see [Here](https://github.com/zwave-js/node-red-contrib-zwave-js/blob/e1862a876571939ebca2503a9f211280a72d5459/zwave-js/zwave-js.js#L73)

**Comment by marcus-j-davies** [comment]
Just spotted a lil mistake.

[this](https://github.com/zwave-js/node-red-contrib-zwave-js/blob/e1862a876571939ebca2503a9f211280a72d5459/zwave-js/zwave-js.js#L139) line needs to be moved to 136.

Do you fancy testing if you can push to dev? - not sure if I have done it right yet.

**Comment by marcus-j-davies** [comment]
Just spotted a lil mistake.

[this](https://github.com/zwave-js/node-red-contrib-zwave-js/blob/e1862a876571939ebca2503a9f211280a72d5459/zwave-js/zwave-js.js#L139) line needs to be moved to

**Comment by hufftheweevil** [comment]
I can do some testing in a few hours. But you're right, no need to update the status if nothing changed. Perhaps it might also be helpful to sort the array after pushing - make it a little easier to spot if a particular node id is on the list.

**Comment by marcus-j-davies** [comment]
No worries,

Let me know if you can push to dev - I haven't opened up `main` for pushing other than myself (Let me keep some control :wink:)

**Comment by hufftheweevil** [comment]
I just realized that testing is not easy. I don't have a 2nd z-wave controller, plus my current one isn't even connected to my dev machine. What kind of setup are you using to do testing/dev?

**Comment by marcus-j-davies** [comment]
No worries, it was more to test your ability to push to dev really. - I will be testing all changes anyway before releasing 1.4, I don't have any special testing rig, I usually just pull my controller from the PI, plug it in to my dev machine, after testing, I then walk around the house waking up devices after restarting Red on the PI.

As for Configuration of nodes, we have the managed CC's of configuration/association/wake interval etc etc.
having a UI - does actually sound awesome though, but yeah, it will need some thought.

I wont be able to do any testing right away for 1.4, I'm bulls deep on the z-wave js side currently, preparing something very special for the lib (and system implementation that uses it) - all will be revealed.
