### ISSUE TITLE
[Help]: update to V9 of ZWave-JS

### ISSUE THREAD

**Issue by ReziioAdmin** [zwave-js/node-red-contrib-zwave-js#200]
### Contact Details (optional)

richard@reziio.com

### How can we help?

Hi Marcus
Two questions:-
1) Are you going to upgrade your node to the latest node-zwave.js ( 9.0)  and do we have to do anything when this is ready ?
2)  We are having issues on some of our larger zwave networks where Node-zwave re-initializes the stick every time we do a deploy on Node-Red.  Is there something you can expose on the controller perhaps to prevent this ?

### Any more details?

If this is specific to some hardware or specific software version, please explain here.

**Comment by marcus-j-davies** [comment]
Hi @ReziioAdmin 

> Are you going to upgrade your node to the latest node-zwave.js ( 9.0) and do we have to do anything when this is ready ?

I am indeed working on support for V9, I am part of the team Behind ZWave-JS, so naturally will follow major version updates.
this will come in the form of V7 of the Node RED Module.

It's actively being worked on, and is making progress.

> do we have to do anything when this is ready

Other than upgrading within the Node RED UI - V7 contains some breaking changes (but you may not use these areas)
the following methods have their responses reviewed and updated
 - **getValue**
 - **getValueMetadata**  
 
 You can see the V7 (ZWJS V9) changelog here - which will get updated, as I progress.
 https://github.com/zwave-js/node-red-contrib-zwave-js/blob/7.0.0/CHANGELOG.md
 
 >  Node-zwave re-initializes the stick every time we do a deploy on Node-Red
 
 This almost sounds like Node RED is set to full deploy - instead of just modified Nodes.
 Node RED will restart any module when
  - The Node is Modifed
  - Set to Full Deploy
  
  The Controller Node (the mothership if you will) will only restart when asked to by Node RED
  
![image](https://user-images.githubusercontent.com/55892693/162386924-fa2bddfa-618c-4640-b7da-fb2e37b54e3b.png)

**Comment by ReziioAdmin** [comment]
Thank you.  I will watch progress on the changelog
