### ISSUE TITLE
Include node name in payload

### ISSUE THREAD

**Issue by crxporter** [zwave-js/node-red-contrib-zwave-js#44]
**Plugin Version**
Version 3.2.2.

I've been using zwavejs2mqtt for nothing but to send my zwave things to nodered. I've just discovered this nodered contrib has added the control panel which is awesome and pretty much the only reason I was using the mqtt option instead of just running it inside nodered.

I'm just getting started out and noticed that the payload looks something like this:
```json
{
  "node": 25,
  "event": "VALUE_UPDATED",
  "timestamp": "2021-04-25T03:17:18.640Z",
  "object": {
    "commandClassName": "Binary Switch",
    "commandClass": 37,
    "endpoint": 0,
    "property": "currentValue",
    "newValue": false,
    "prevValue": true,
    "propertyName": "currentValue"
  }
}
```

My feature request is to add something like `nodeName` similar to how you have `commandClassName`. New payload would look something like this and be a lot easier to work with, having names instead of just node numbers:

```json
{
  "nodeName": "DeskLight",
  "node": 25,
  "event": "VALUE_UPDATED",
  "timestamp": "2021-04-25T03:17:18.640Z",
  "object": {
    "commandClassName": "Binary Switch",
    "commandClass": 37,
    "endpoint": 0,
    "property": "currentValue",
    "newValue": false,
    "prevValue": true,
    "propertyName": "currentValue"
  }
}
```

Thanks for your hard work! I look forward to moving over to this setup!

**Comment by marcus-j-davies** [comment]
Hey!

Your timing is perfect.
The Node Red flows page, has a slight difference in how it renders some markdown compared to others
(due to the renderer they use), so have been searching for a reason to push a new version to get it <del>corrected</del> compatible. 

Adding the node name should be a breeze - I'll get it done today!

The `object` component, is the unmodified (in most cases) payload from z-wave js.
So this can differ in content, based on what event from z-wave js occurs.

If it also helps your setup - the `zwave-device` node, allows a single device approach (ensure the main node is deployed first)

**Comment by marcus-j-davies** [comment]
And with that - it's done.
I have also added the **nodeLocation**

```json
{
  "node": 22,
  "nodeName": "Security Keypad",
  "nodeLocation": "The Red Room",
  "event": "NOTIFICATION",
  "timestamp": "2021-04-25T09:54:21.320Z",
  "object": {
    "ccId": 111,
    "args": {
      "eventType": 25,
      "dataType": 0
    }
  }
}
```

I'll keep this open, until you have had a chance to spin it up (v3.2.3)
The update should be available in node-red  

  - 3.2.3
    - Added **nodeName** and **nodeLocation** to incoming z-wave events (if they are set).  
    - Added ability to set Node Location in the UI.  
    - Bump Z-Wave JS
    - Fixed read me compatibility with **flows.nodered.org**

**Comment by crxporter** [comment]
This is great! Works like a charm.
