### ISSUE TITLE
Add more Controller info to UI

### ISSUE THREAD

**Issue by marcus-j-davies** [zwave-js/node-red-contrib-zwave-js#67]
@crxporter

for 3.8.0 (next release)

**Comment by marcus-j-davies** [comment]
@crxporter.

I'm thinking of removing the device description (I think model number is enough).
device description will be replaced with the firmware version.

Thoughts?

![image](https://user-images.githubusercontent.com/55892693/121687567-6a3c5a00-caba-11eb-9788-7146f01cc303.png)

**Comment by crxporter** [comment]
We wouldn't loose much of anything if the current second line was hover-text for the first line. Is that difficult?

**Comment by marcus-j-davies** [comment]
Not difficult at all - just fiddly

**Comment by crxporter** [comment]
Your suggestion is good. All the information is in the values tables anyway, right?

**Comment by marcus-j-davies** [comment]
Yep, it's only the description of the devices being sacrificed - which I don't think is crucial.

**Comment by crxporter** [comment]
Full disclosure: I was still mostly asleep when I made the first comment about hover text. 

Highlighting firmware is cool, but gives me another question... do you have any plans to add firmware updates?

Do we have cli-level access to Zwave-js while it runs in nodered? Maybe that would be a better option for firmware instead of adding it inside NR. 

Of course we could just stop nodered, update with cli, then head back to nodered... 

Sorry now I'm getting sidetracked. This can be another issue for another time.

**Comment by marcus-j-davies** [comment]
So,

Adding firmware update support, has been in the back of my mind.
However, it is a delicate process, and I want to implement it correctly, and most importantly, implement it to be stable.

Z-Wave JS, has the methods, but it wants the binary file/firmware file etc etc.
This is where my "focus" is - trying to make it as simple (and trouble free as possible).

its on my todo - Watch this space 👍
